# Site
repository: atishayjain708/atishayjain708.github.io
# favicon: images/favicon.ico

# Personal info
name: Atishay Jain
title: Senior Network System Administrator
email: atishayjain708@gmail.com
website: atishayjain708.github.io

# Social links
twitter_username: _atishayJain
github_username:  atishayjain708
# dribbble_username: jekyll
facebook_username: Atishay5
# flickr_username: jekyll
instagram_username: _atishay.jain
linkedin_username: atishay5
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Atishay Jain - a Computer Science engineering Junior year student. I have experience working with Python and using and deploying end to end solutions, mostly using web as the platform. Currently I'm working in and increasing my knowledge of the machine learning and data-science domain.
  I have experience working with Django, Docker, using Jekyll templates and Tensorflow.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
